### ISSUE TITLE
webchat is stuck randomly

### ISSUE THREAD

**Issue by tufeigunchu** [Drpto/device_xiaomi_stone#1]
with below log:
`02-02 11:45:38.273 11299 11624 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.274   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.275 11299 11624 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.276   593  4844 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.276   593  4844 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
02-02 11:45:38.352 13999 14033 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.353   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.354 13999 14033 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.355   593  4847 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.355   593  4847 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
02-02 11:45:38.358 12931 13033 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.358   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.359 12931 13033 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.360   593  4848 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.360   593  4848 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
02-02 11:45:38.372 13223 13364 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.373   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.373 13223 13364 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.374   593  4850 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.375   593  4850 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.`

**Comment by tufeigunchu** [comment]
02-02 11:45:38.273 11299 11624 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.274   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.275 11299 11624 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.276   593  4844 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.276   593  4844 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
02-02 11:45:38.352 13999 14033 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.353   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.354 13999 14033 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.355   593  4847 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.355   593  4847 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
02-02 11:45:38.358 12931 13033 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.358   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.359 12931 13033 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.360   593  4848 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.360   593  4848 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
02-02 11:45:38.372 13223 13364 W HidlServiceManagement: Waited one second for android.hardware.drm@1.0::IDrmFactory/wfdhdcp
02-02 11:45:38.373   593   593 I hwservicemanager: Since android.hardware.drm@1.0::IDrmFactory/wfdhdcp is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
02-02 11:45:38.373 13223 13364 I HidlServiceManagement: getService: Trying again for android.hardware.drm@1.0::IDrmFactory/wfdhdcp...
02-02 11:45:38.374   593  4850 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.drm@1.0::IDrmFactory/wfdhdcp": error code: 0x20
02-02 11:45:38.375   593  4850 I hwservicemanager: Tried to start android.hardware.drm@1.0::IDrmFactory/wfdhdcp as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.

**Comment by Drpto** [comment]
Will solved soon
